spring:

  # =======================
  # DATABASE PROD
  # =======================
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  # =======================
  # REDIS PROD
  # =======================
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

  # =======================
  # KEYCLOAK PROD
  # =======================
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

# =======================
# LOGGING PROD
# =======================
logging:
  level:
    root: WARN
    com.siide.linkup: INFO

# =======================
# ACTUATOR PROD
# =======================
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false